import { parseAbi } from 'viem';
export const sanctionsResolverV2Abi = parseAbi([
    'struct Designation { bytes32 attestationUID; address attester; uint64 attestedAt; }',
    'function isSanctioned(address account) view returns (bool)',
    'function isSanctionedBatch(address[] accounts) view returns (bool[])',
    'function getDesignation(address account) view returns (Designation)',
    'function accountKey(bytes32 network, string account) pure returns (bytes32)',
    'function supportsNetwork(bytes32 network) pure returns (bool)',
    'function isSanctionedAccount(bytes32 network, string account) view returns (bool)',
    'function isSanctionedKey(bytes32 key) view returns (bool)',
    'function isSanctionedKeyBatch(bytes32[] keys) view returns (bool[])',
    'function getDesignationByKey(bytes32 key) view returns (Designation)',
    'function sanctionedCount() view returns (uint256)',
    'function sanctionedAddresses() view returns (address[])',
    'function sanctionedRange(uint256 offset, uint256 limit) view returns (address[])',
    'function sanctionedAccountCount() view returns (uint256)',
    'function sanctionedKeyRange(uint256 offset, uint256 limit) view returns (bytes32[])',
    'struct Publication { string source; string sourceUrl; bytes32 sourceSha256; bytes32 comparisonSourceSha256; uint64 sourcePublishedAt; bytes32 previousPublication; uint8 kind; uint32 chunkIndex; uint32 chunkCount; string[] sourceUIDs; string[] categories; uint64[] designatedAt; string[] entityNetworks; string[] addedAccounts; uint32[] entityIndices; string[] removedNetworks; string[] removedAccounts; }',
    'function getPublicationChunk(bytes32 uid) view returns (Publication)',
    'event PublicationChunkApplied(bytes32 indexed publicationId,bytes32 indexed uid,uint32 chunkIndex)',
    'function getAccountByKey(bytes32 key) view returns (string network,string account,string sourceUID)',
    'function latestPublication() view returns (bytes32)',
    'function pendingPublication() view returns (bytes32)',
    'function publications(bytes32 id) view returns (bytes32 firstUID,bytes32 lastUID,bytes32 sourceSha256,uint64 sourcePublishedAt,uint32 processedChunks,uint32 chunkCount,uint8 kind,uint32 addedKeys,uint32 removedKeys)',
    'event PublicationCompleted(bytes32 indexed publicationId,bytes32 indexed sourceSha256,uint64 sourcePublishedAt,uint8 kind,uint32 addedKeys,uint32 removedKeys)',
    'function schemaUID() view returns (bytes32)',
    'function getEAS() view returns (address)',
]);
